#!/bin/bash

FOLDER="test"
folder_name=$FOLDER

file="FROM node:10.16.3-alpine
\nARG FOLDER
\nENV folder_name=$FOLDER
\nRUN echo value-${folder_name}"

echo -e $file | docker build --no-cache --rm --force-rm -


